"""Stable operational error codes."""

SOURCE_API_FAILURE = "SOURCE_API_FAILURE"
SOURCE_DATA_STALE = "SOURCE_DATA_STALE"
HOPSWORKS_UNAVAILABLE = "HOPSWORKS_UNAVAILABLE"
MODEL_RESOLUTION_FAILED = "MODEL_RESOLUTION_FAILED"
INFERENCE_FAILED = "INFERENCE_FAILED"
AQI_PIPELINE_FAILED = "AQI_PIPELINE_FAILED"
ARTIFACT_PUBLICATION_FAILED = (
    "ARTIFACT_PUBLICATION_FAILED"
)
MODEL_TRAINING_FAILED = "MODEL_TRAINING_FAILED"
DEPLOYMENT_FAILED = "DEPLOYMENT_FAILED"
HEALTH_CHECK_FAILED = "HEALTH_CHECK_FAILED"
CONFIGURATION_INVALID = "CONFIGURATION_INVALID"