"""Durable notification delivery for production-health incidents."""

from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timezone
from typing import Any

from app.artifacts.repository import (
    ArtifactRepository,
)
from app.notifications.email import (
    AzureEmailClient,
)
from app.notifications.webhook import (
    JsonWebhookClient,
)


NOTIFICATION_OUTBOX_PATH = (
    "production-health/notifications/outbox.json"
)

NOTIFICATION_RECEIPT_PREFIX = (
    "production-health/notifications/receipts"
)

SUPPORTED_NOTIFICATION_TYPES = {
    "INCIDENT_OPENED",
    "INCIDENT_CHANGED",
    "INCIDENT_RESOLVED",
}


class HealthNotificationError(RuntimeError):
    """Raised when incident notification handling fails."""


def utc_now() -> datetime:
    """Return current timezone-aware UTC time."""

    return datetime.now(
        timezone.utc
    )


def read_environment_value(
    name: str,
    *,
    default: str | None = None,
) -> str | None:
    """Read and normalize one environment variable."""

    value = os.getenv(
        name,
        default,
    )

    if value is None:
        return None

    normalized = value.strip()

    return normalized or None


def read_timeout_seconds() -> float:
    """Read the optional webhook delivery timeout."""

    raw_value = read_environment_value(
        "PRODUCTION_HEALTH_WEBHOOK_TIMEOUT_SECONDS",
        default="15",
    )

    try:
        timeout = float(
            raw_value or "15"
        )
    except ValueError as error:
        raise HealthNotificationError(
            "PRODUCTION_HEALTH_WEBHOOK_TIMEOUT_SECONDS "
            "must be numeric."
        ) from error

    if timeout <= 0:
        raise HealthNotificationError(
            "Webhook timeout must be positive."
        )

    return timeout


def read_notification_channel() -> str:
    """Return configured production-health notification channel."""

    channel = (
        read_environment_value(
            "PRODUCTION_HEALTH_NOTIFICATION_CHANNEL",
            default="disabled",
        )
        or "disabled"
    ).lower()

    if channel not in {
        "disabled",
        "webhook",
        "email",
    }:
        raise HealthNotificationError(
            "PRODUCTION_HEALTH_NOTIFICATION_CHANNEL "
            "must be disabled, webhook, or email."
        )

    return channel


def build_email_subject(
    event: dict[str, Any],
) -> str:
    """Build one filter-friendly production alert subject."""

    status = str(
        event.get(
            "overall_component_status",
            "UNKNOWN",
        )
    )

    event_type = str(
        event.get(
            "event_type",
            "UNKNOWN",
        )
    )

    if event_type == "INCIDENT_RESOLVED":
        status_label = "RECOVERED"
    else:
        status_label = status

    return (
        "[Pearls AQI Alert]"
        f"[{status_label}] "
        f"{event_type}"
    )

def build_email_body(
    event: dict[str, Any],
) -> str:
    """Build plain-text operational alert email."""

    lines = [
        "Pearls AQI Predictor - Production Alert",
        "",
        f"Event: {event.get('event_type')}",
        f"Incident: {event.get('incident_id')}",
        (
            "Overall status: "
            f"{event.get('overall_component_status')}"
        ),
        (
            "Health run: "
            f"{event.get('health_run_id')}"
        ),
        "",
        "Affected components:",
    ]

    components = event.get(
        "components",
        [],
    )

    if isinstance(
        components,
        list,
    ):
        for component in components:
            if not isinstance(
                component,
                dict,
            ):
                continue

            lines.append(
                "- "
                f"{component.get('category')}/"
                f"{component.get('name')}: "
                f"{component.get('status')}"
            )

            reason = component.get(
                "reason"
            )

            if reason:
                lines.append(
                    f"  {reason}"
                )

    recommendations = event.get(
        "recommendations",
        [],
    )

    if (
        isinstance(
            recommendations,
            list,
        )
        and recommendations
    ):
        lines.extend(
            [
                "",
                "Recommended actions:",
            ]
        )

        for recommendation in recommendations:
            lines.append(
                f"- {recommendation}"
            )

    lines.extend(
        [
            "",
            (
                "This message was generated by "
                "the Pearls AQI production monitor."
            ),
        ]
    )

    return "\n".join(
        lines
    )


def create_email_client() -> (
    AzureEmailClient | None
):
    """Create the permanent email notification client."""

    if (
        read_notification_channel()
        != "email"
    ):
        return None

    endpoint = (
        read_environment_value(
            "PRODUCTION_HEALTH_EMAIL_ENDPOINT"
        )
    )

    sender = (
        read_environment_value(
            "PRODUCTION_HEALTH_EMAIL_SENDER"
        )
    )

    recipient = (
        read_environment_value(
            "PRODUCTION_HEALTH_EMAIL_RECIPIENT"
        )
    )

    if (
        endpoint is None
        or sender is None
        or recipient is None
    ):
        raise HealthNotificationError(
            "Email notifications require "
            "PRODUCTION_HEALTH_EMAIL_ENDPOINT, "
            "PRODUCTION_HEALTH_EMAIL_SENDER, and "
            "PRODUCTION_HEALTH_EMAIL_RECIPIENT."
        )

    return AzureEmailClient(
        endpoint=endpoint,
        sender_address=sender,
        recipient_address=recipient,
        managed_identity_client_id=(
            read_environment_value(
                "AZURE_CLIENT_ID"
            )
        ),
    )


def create_webhook_client() -> (
    JsonWebhookClient | None
):
    """Create the optional webhook notification client."""

    if (
        read_notification_channel()
        != "webhook"
    ):
        return None

    url = read_environment_value(
        "PRODUCTION_HEALTH_WEBHOOK_URL"
    )

    if url is None:
        raise HealthNotificationError(
            "PRODUCTION_HEALTH_WEBHOOK_URL is required "
            "when webhook notification delivery is selected."
        )

    bearer_token = read_environment_value(
        "PRODUCTION_HEALTH_WEBHOOK_BEARER_TOKEN"
    )

    return JsonWebhookClient(
        url=url,
        timeout_seconds=(
            read_timeout_seconds()
        ),
        bearer_token=bearer_token,
    )


def load_outbox(
    repository: ArtifactRepository,
) -> dict[str, Any]:
    """Load the durable notification outbox."""

    if not repository.exists(
        NOTIFICATION_OUTBOX_PATH
    ):
        return {
            "version": 1,
            "pending": [],
            "updated_at_utc": (
                utc_now().isoformat()
            ),
        }

    outbox = repository.download_json(
        NOTIFICATION_OUTBOX_PATH
    )

    pending = outbox.get(
        "pending"
    )

    if not isinstance(
        pending,
        list,
    ):
        raise HealthNotificationError(
            "Notification outbox pending value "
            "must be a list."
        )

    return {
        "version": 1,
        "pending": [
            item
            for item in pending
            if isinstance(
                item,
                dict,
            )
        ],
        "updated_at_utc": outbox.get(
            "updated_at_utc"
        ),
    }


def save_outbox(
    *,
    repository: ArtifactRepository,
    pending: list[dict[str, Any]],
    now: datetime,
) -> None:
    """Persist mutable notification outbox state."""

    repository.upload_json(
        payload={
            "version": 1,
            "pending": pending,
            "pending_count": len(
                pending
            ),
            "updated_at_utc": (
                now.isoformat()
            ),
        },
        destination_path=(
            NOTIFICATION_OUTBOX_PATH
        ),
        overwrite=True,
    )


def build_notification_id(
    *,
    notification_type: str,
    incident_id: str,
    history_path: str | None,
) -> str:
    """Build a stable notification identifier."""

    payload = {
        "notification_type": (
            notification_type
        ),
        "incident_id": (
            incident_id
        ),
        "history_path": (
            history_path
        ),
    }

    digest = hashlib.sha256(
        json.dumps(
            payload,
            sort_keys=True,
            separators=(",", ":"),
        ).encode(
            "utf-8"
        )
    ).hexdigest()

    return (
        f"{notification_type.lower()}_"
        f"{digest[:20]}"
    )


def build_notification_event(
    *,
    incident_evaluation: dict[str, Any],
    health_report: dict[str, Any],
    health_run_id: str,
    now: datetime,
) -> dict[str, Any] | None:
    """Build a notification event when delivery is required."""

    if not bool(
        incident_evaluation.get(
            "notification_required"
        )
    ):
        return None

    notification_type = str(
        incident_evaluation.get(
            "notification_type",
            "",
        )
    )

    if (
        notification_type
        not in SUPPORTED_NOTIFICATION_TYPES
    ):
        raise HealthNotificationError(
            "Unsupported health notification type: "
            f"{notification_type!r}"
        )

    incident = incident_evaluation.get(
        "incident"
    )

    if not isinstance(
        incident,
        dict,
    ):
        raise HealthNotificationError(
            "Notification event requires incident data."
        )

    incident_id = str(
        incident.get(
            "incident_id",
            "",
        )
    )

    if not incident_id:
        raise HealthNotificationError(
            "Incident does not contain an incident ID."
        )

    history_path_value = (
        incident_evaluation.get(
            "history_path"
        )
    )

    history_path = (
        str(
            history_path_value
        )
        if history_path_value
        else None
    )

    notification_id = (
        build_notification_id(
            notification_type=(
                notification_type
            ),
            incident_id=(
                incident_id
            ),
            history_path=(
                history_path
            ),
        )
    )

    components = (
        incident_evaluation.get(
            "unhealthy_components",
            [],
        )
    )

    return {
        "notification_id": (
            notification_id
        ),
        "notification_channel": (
            read_notification_channel()
        ),
        "schema_version": 2,
        "event_type": (
            notification_type
        ),
        "created_at_utc": (
            now.isoformat()
        ),
        "environment": (
            read_environment_value(
                "APP_ENV",
                default="development",
            )
            or "development"
        ),
        "project": "pearls-aqi",
        "health_run_id": (
            health_run_id
        ),
        "health_status": (
            health_report.get(
                "status"
            )
        ),
        "overall_component_status": (
            health_report.get(
                "overall_component_status"
            )
        ),
        "incident_id": (
            incident_id
        ),
        "incident_status": (
            incident.get(
                "status"
            )
        ),
        "opened_at_utc": (
            incident.get(
                "opened_at_utc"
            )
        ),
        "resolved_at_utc": (
            incident.get(
                "resolved_at_utc"
            )
        ),
        "occurrence_count": (
            incident.get(
                "occurrence_count"
            )
        ),
        "history_path": (
            history_path
        ),
        "components": (
            components
            if isinstance(
                components,
                list,
            )
            else []
        ),
        "recommendations": (
            health_report.get(
                "recommendations",
                [],
            )
        ),
    }


def enqueue_notification(
    *,
    repository: ArtifactRepository,
    event: dict[str, Any] | None,
    now: datetime,
) -> dict[str, Any]:
    """Add one event unless already pending or delivered."""

    outbox = load_outbox(
        repository
    )

    pending = list(
        outbox["pending"]
    )

    if event is None:
        return {
            "pending": pending,
            "enqueued": False,
            "notification_id": None,
        }

    notification_id = str(
        event["notification_id"]
    )

    receipt_path = (
        f"{NOTIFICATION_RECEIPT_PREFIX}/"
        f"{notification_id}.json"
    )

    already_pending = any(
        item.get(
            "notification_id"
        )
        == notification_id
        for item in pending
    )

    already_delivered = (
        repository.exists(
            receipt_path
        )
    )

    if (
        not already_pending
        and not already_delivered
    ):
        pending.append(
            event
        )

        save_outbox(
            repository=repository,
            pending=pending,
            now=now,
        )

        return {
            "pending": pending,
            "enqueued": True,
            "notification_id": (
                notification_id
            ),
        }

    return {
        "pending": pending,
        "enqueued": False,
        "notification_id": (
            notification_id
        ),
    }


def deliver_pending_notifications(
    *,
    repository: ArtifactRepository,
    client: JsonWebhookClient | None,
    now: datetime,
) -> dict[str, Any]:
    """Deliver durable pending health events through webhook."""

    outbox = load_outbox(
        repository
    )

    pending = list(
        outbox["pending"]
    )

    if client is None:
        return {
            "status": "WEBHOOK_DISABLED",
            "channel": "webhook",
            "attempted_count": 0,
            "delivered_count": 0,
            "failed_count": 0,
            "pending_count": len(
                pending
            ),
            "delivered": [],
            "failures": [],
        }

    remaining: list[
        dict[str, Any]
    ] = []

    delivered: list[
        dict[str, Any]
    ] = []

    failures: list[
        dict[str, Any]
    ] = []

    for event in pending:
        notification_id = str(
            event.get(
                "notification_id",
                "",
            )
        )

        if not notification_id:
            remaining.append(
                event
            )

            failures.append(
                {
                    "notification_id": None,
                    "error_type": (
                        "HealthNotificationError"
                    ),
                    "error_message": (
                        "Pending notification has "
                        "no notification ID."
                    ),
                }
            )

            continue

        receipt_path = (
            f"{NOTIFICATION_RECEIPT_PREFIX}/"
            f"{notification_id}.json"
        )

        if repository.exists(
            receipt_path
        ):
            delivered.append(
                {
                    "notification_id": (
                        notification_id
                    ),
                    "receipt_path": (
                        receipt_path
                    ),
                    "recovered_from_receipt": (
                        True
                    ),
                }
            )

            continue

        try:
            result = client.send(
                payload=event,
                idempotency_key=(
                    notification_id
                ),
            )

            receipt = {
                "notification_id": (
                    notification_id
                ),
                "channel": "webhook",
                "event_type": (
                    event.get(
                        "event_type"
                    )
                ),
                "incident_id": (
                    event.get(
                        "incident_id"
                    )
                ),
                "delivered_at_utc": (
                    now.isoformat()
                ),
                "provider": (
                    "http_webhook"
                ),
                "provider_status": (
                    "SUCCEEDED"
                ),
                "provider_message_id": (
                    None
                ),
                "provider_details": {
                    "http_status_code": (
                        result.status_code
                    ),
                    "idempotency_key": (
                        result.idempotency_key
                    ),
                    "response_body": (
                        result.response_body[
                            :1000
                        ]
                    ),
                },
            }

            repository.upload_json(
                payload=receipt,
                destination_path=(
                    receipt_path
                ),
                overwrite=False,
            )

            delivered.append(
                {
                    "notification_id": (
                        notification_id
                    ),
                    "receipt_path": (
                        receipt_path
                    ),
                    "http_status_code": (
                        result.status_code
                    ),
                    "recovered_from_receipt": (
                        False
                    ),
                }
            )

        except Exception as error:
            remaining.append(
                event
            )

            failures.append(
                {
                    "notification_id": (
                        notification_id
                    ),
                    "error_type": (
                        type(error).__name__
                    ),
                    "error_message": str(
                        error
                    ),
                }
            )

    save_outbox(
        repository=repository,
        pending=remaining,
        now=now,
    )

    if failures:
        status = (
            "WEBHOOK_DELIVERY_FAILED"
        )

    elif delivered:
        status = (
            "WEBHOOK_DELIVERY_COMPLETED"
        )

    else:
        status = (
            "WEBHOOK_NOTHING_TO_DELIVER"
        )

    return {
        "status": status,
        "channel": "webhook",
        "attempted_count": len(
            pending
        ),
        "delivered_count": len(
            delivered
        ),
        "failed_count": len(
            failures
        ),
        "pending_count": len(
            remaining
        ),
        "delivered": delivered,
        "failures": failures,
    }


def deliver_pending_email_notifications(
    *,
    repository: ArtifactRepository,
    client: AzureEmailClient | None,
    now: datetime,
) -> dict[str, Any]:
    """Deliver durable pending health events through email."""

    outbox = load_outbox(
        repository
    )

    pending = list(
        outbox["pending"]
    )

    if client is None:
        return {
            "status": "EMAIL_DISABLED",
            "channel": "email",
            "attempted_count": 0,
            "delivered_count": 0,
            "failed_count": 0,
            "pending_count": len(
                pending
            ),
            "delivered": [],
            "failures": [],
        }

    remaining: list[
        dict[str, Any]
    ] = []

    delivered: list[
        dict[str, Any]
    ] = []

    failures: list[
        dict[str, Any]
    ] = []

    for event in pending:
        notification_id = str(
            event.get(
                "notification_id",
                "",
            )
        )

        if not notification_id:
            remaining.append(
                event
            )

            failures.append(
                {
                    "notification_id": None,
                    "error_type": (
                        "HealthNotificationError"
                    ),
                    "error_message": (
                        "Pending notification has "
                        "no notification ID."
                    ),
                }
            )

            continue

        receipt_path = (
            f"{NOTIFICATION_RECEIPT_PREFIX}/"
            f"{notification_id}.json"
        )

        if repository.exists(
            receipt_path
        ):
            delivered.append(
                {
                    "notification_id": (
                        notification_id
                    ),
                    "receipt_path": (
                        receipt_path
                    ),
                    "recovered_from_receipt": (
                        True
                    ),
                }
            )

            continue

        try:
            result = client.send(
                subject=(
                    build_email_subject(
                        event
                    )
                ),
                plain_text=(
                    build_email_body(
                        event
                    )
                ),
            )

            receipt = {
                "notification_id": (
                    notification_id
                ),
                "channel": "email",
                "event_type": (
                    event.get(
                        "event_type"
                    )
                ),
                "incident_id": (
                    event.get(
                        "incident_id"
                    )
                ),
                "delivered_at_utc": (
                    now.isoformat()
                ),
                "provider": (
                    "azure_communication_services"
                ),
                "provider_message_id": (
                    result.message_id
                ),
                "provider_status": (
                    result.status
                ),
            }

            repository.upload_json(
                payload=receipt,
                destination_path=(
                    receipt_path
                ),
                overwrite=False,
            )

            delivered.append(
                {
                    "notification_id": (
                        notification_id
                    ),
                    "receipt_path": (
                        receipt_path
                    ),
                    "provider_message_id": (
                        result.message_id
                    ),
                    "provider_status": (
                        result.status
                    ),
                    "recovered_from_receipt": (
                        False
                    ),
                }
            )

        except Exception as error:
            remaining.append(
                event
            )

            failures.append(
                {
                    "notification_id": (
                        notification_id
                    ),
                    "error_type": (
                        type(error).__name__
                    ),
                    "error_message": str(
                        error
                    ),
                }
            )

    save_outbox(
        repository=repository,
        pending=remaining,
        now=now,
    )

    if failures:
        status = (
            "EMAIL_DELIVERY_FAILED"
        )

    elif delivered:
        status = (
            "EMAIL_DELIVERY_COMPLETED"
        )

    else:
        status = (
            "EMAIL_NOTHING_TO_DELIVER"
        )

    return {
        "status": status,
        "channel": "email",
        "attempted_count": len(
            pending
        ),
        "delivered_count": len(
            delivered
        ),
        "failed_count": len(
            failures
        ),
        "pending_count": len(
            remaining
        ),
        "delivered": delivered,
        "failures": failures,
    }


def process_health_notifications(
    *,
    repository: ArtifactRepository,
    incident_evaluation: dict[str, Any],
    health_report: dict[str, Any],
    health_run_id: str,
    now: datetime,
) -> dict[str, Any]:
    """Enqueue the current event and process all pending events."""

    event = build_notification_event(
        incident_evaluation=(
            incident_evaluation
        ),
        health_report=(
            health_report
        ),
        health_run_id=(
            health_run_id
        ),
        now=(
            now
        ),
    )

    enqueue_result = (
        enqueue_notification(
            repository=(
                repository
            ),
            event=(
                event
            ),
            now=(
                now
            ),
        )
    )

    channel = (
        read_notification_channel()
    )

    if channel == "email":
        email_client = (
            create_email_client()
        )

        delivery = (
            deliver_pending_email_notifications(
                repository=(
                    repository
                ),
                client=(
                    email_client
                ),
                now=(
                    now
                ),
            )
        )

    elif channel == "webhook":
        webhook_client = (
            create_webhook_client()
        )

        delivery = (
            deliver_pending_notifications(
                repository=(
                    repository
                ),
                client=(
                    webhook_client
                ),
                now=(
                    now
                ),
            )
        )

    else:
        outbox = load_outbox(
            repository
        )

        delivery = {
            "status": (
                "NOTIFICATION_DELIVERY_DISABLED"
            ),
            "channel": (
                "disabled"
            ),
            "attempted_count": 0,
            "delivered_count": 0,
            "failed_count": 0,
            "pending_count": len(
                outbox[
                    "pending"
                ]
            ),
            "delivered": [],
            "failures": [],
        }

    return {
        "event_created": (
            event is not None
        ),
        "notification_id": (
            event.get(
                "notification_id"
            )
            if event is not None
            else None
        ),
        "enqueued": (
            enqueue_result[
                "enqueued"
            ]
        ),
        **delivery,
    }